-- MySQL Script generated by MySQL Workbench
-- Mon Feb 21 12:29:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db8
-- -----------------------------------------------------
DROP DATABASE IF EXISTS db8;
-- -----------------------------------------------------
-- Schema db8
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db8` DEFAULT CHARACTER SET utf8 ;
USE `db8` ;

-- -----------------------------------------------------
-- Table `db8`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db8`.`member` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(50) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(50) NULL,
  `email` VARCHAR(100) NULL,
  `gender` VARCHAR(10) NULL,
  `rdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `profile` LONGBLOB NULL,
  PRIMARY KEY (`no`),
  UNIQUE INDEX `userid_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db8`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db8`.`schedule` (
  `sno` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(45) NULL,
  `startDate` VARCHAR(50) NULL,
  `EndDate` VARCHAR(50) NULL,
  `memo` LONGTEXT NULL,
  `user_no` INT NOT NULL,
  PRIMARY KEY (`sno`),
  INDEX `fk_schedule_user_idx` (`user_no` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_user`
    FOREIGN KEY (`user_no`)
    REFERENCES `db8`.`member` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db8`.`checklist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db8`.`checklist` (
  `chno` INT NOT NULL AUTO_INCREMENT,
  `id` TINYINT(1) NULL,
  `creditcardcash` TINYINT(1) NULL,
  `charger` TINYINT(1) NULL,
  `portablecharger` TINYINT(1) NULL,
  `mask` TINYINT(1) NULL,
  `umbrella` TINYINT(1) NULL,
  `camera` TINYINT(1) NULL,
  `cloth` TINYINT(1) NULL,
  `pajamas` TINYINT(1) NULL,
  `underwear` TINYINT(1) NULL,
  `socks` TINYINT(1) NULL,
  `toothbrush` TINYINT(1) NULL,
  `showersupplies` TINYINT(1) NULL,
  `cosmetics` TINYINT(1) NULL,
  `dryer` TINYINT(1) NULL,
  `shaver` TINYINT(1) NULL,
  `emergencymedicine` TINYINT(1) NULL,
  `tissue` TINYINT(1) NULL,
  `eyepatch` TINYINT(1) NULL,
  `neckpillow` TINYINT(1) NULL,
  `blanket` TINYINT(1) NULL,
  `user_no` INT NOT NULL,
  `firstlistblank` VARCHAR(150) NULL,
  `secondlistblank` VARCHAR(150) NULL,
  `thirdlistblank` VARCHAR(150) NULL,
  `fourthlistblank` VARCHAR(150) NULL,
  `memojang` longtext null,
  PRIMARY KEY (`chno`),
  INDEX `fk_checklist_user1_idx` (`user_no` ASC) VISIBLE,
  CONSTRAINT `fk_checklist_user1`
    FOREIGN KEY (`user_no`)
    REFERENCES `db8`.`member` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db8`.`notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db8`.`notice` (
  `n_no` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NULL,
  `contents` LONGTEXT NULL,
  `views` INT NULL DEFAULT 0,
  `date` TIMESTAMP NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY (`n_no`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db8`.`qnaboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db8`.`qnaboard` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(170) NULL,
  `contents` LONGTEXT NULL,
  `writer` INT NOT NULL,
  `rdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `views` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`no`),
  INDEX `fk_qna_user1_idx` (`writer` ASC) VISIBLE,
  CONSTRAINT `fk_qna_user1`
    FOREIGN KEY (`writer`)
    REFERENCES `db8`.`member` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db8`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db8`.`city` (
  `cno` INT not NULL auto_increment,
  `cname` VARCHAR(45) NULL,
  PRIMARY KEY (`cno`))
ENGINE = InnoDB;

--------------------------------------------------------
-- Table `db8`.`local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db8`.`local` (
   `lno` INT NOT NULL AUTO_INCREMENT,
  `lname` VARCHAR(50) NULL,
  `city_cno` INT NOT NULL,
  `x` varchar(50) not null,
  `y` varchar(50) not null,
  PRIMARY KEY (`lno`),
  INDEX `fk_local_city1_idx` (`city_cno` ASC) VISIBLE,
  CONSTRAINT `fk_local_city1`
    FOREIGN KEY (`city_cno`)
    REFERENCES `db8`.`city` (`cno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db8`.`qna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db8`.`qna` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `contents` LONGTEXT NOT NULL,
  `rdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`no`),
  CONSTRAINT `fk_qna_qnaboard1`
    FOREIGN KEY (`no`)
    REFERENCES `db8`.`qnaboard` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-------------------------------------------------

